- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Varibles
      include_vars: idea/vars/vpc_setup.txt

    - name: Create Vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tendency: default
        state: "{{state}}"
      register: vpcout
